baseURL = "https://ori.codes/"
languageCode = "en-us"
title = "Ori Codes"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 

  # Useful to give opportunity to people to create merge request for your doc.

  # See the config.toml file from this documentation site to have an example.

  editURL = ""

  # Author of the site, will be used in meta information

  author = "ori"

  # Description of the site, will be used in meta information

  description = "Ori's self-driving RC car"

  # Shows a checkmark for visited pages on the menu

  showVisitedLinks = true

  # Disable search function. It will hide search bar

  disableSearch = false

  # Javascript and CSS cache are automatically busted when new version of site is generated. 

  # Set this to true to disable this behavior (some proxies don't handle well this optimization)

  disableAssetsBusting = true

  # Set this to true to disable copy-to-clipboard button for inline code.

  disableInlineCopyToClipBoard = true

  # A title for shortcuts in menu is set by default. Set this to true to disable it. 

  disableShortcutsTitle = true

  # When using mulitlingual website, disable the switch language button.

  disableLanguageSwitchingButton = false

  # Hide breadcrumbs in the header and only show the current page title

  disableBreadcrumb = true

  # Hide Next and Previous page buttons normally displayed full height beside content

  disableNextPrev = false

  # Order sections in menu by "weight" or "title". Default to "weight"

  ordersectionsby = "weight"

  # Change default color scheme with a variant one. Can be "red", "blue", "green".

  themeVariant = "mine"
  
 # English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
	[Languages.en]
	title = "Ori Codes"
	weight = 1
	languageName = "English"
	contentDir = "content/english"

	[Languages.hr]
	title = "Ori Codes"
	weight = 2
	languageName = "Hrvatski"
	contentDir = "content/hrvatski"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
url = "https://github.com/ivanorsolic"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fab fa-twitter'></i> Twitter"
identifier = "ds"
url = "https://twitter.com/ivanorsolic"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-tasks'></i> Other stuff"
url = "https://ivanorsolic.github.io"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-file'></i> My CV"
url = "https://drive.google.com/file/d/1c4F5kfnWZnwQciP8gKyKunzDOqBJ5gDM/view?usp=sharing"
weight = 20

[markup.goldmark.renderer]
unsafe=true
[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "dracula"
  tabWidth = 4